(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/statistics/components/taskColumn"],{"00d2":function(t,e,n){"use strict";var a=n("22c1"),r=n.n(a);r.a},"22c1":function(t,e,n){},"22f0":function(t,e,n){"use strict";n.r(e);var a=n("7506"),r=n("725e");for(var i in r)["default"].indexOf(i)<0&&function(t){n.d(e,t,(function(){return r[t]}))}(i);n("00d2");var o=n("828b"),u=Object(o["a"])(r["default"],a["b"],a["c"],!1,null,"1e0a0c91",null,!1,a["a"],void 0);e["default"]=u.exports},"725e":function(t,e,n){"use strict";n.r(e);var a=n("7a9d"),r=n.n(a);for(var i in a)["default"].indexOf(i)<0&&function(t){n.d(e,t,(function(){return a[t]}))}(i);e["default"]=r.a},7506:function(t,e,n){"use strict";n.d(e,"b",(function(){return r})),n.d(e,"c",(function(){return i})),n.d(e,"a",(function(){return a}));var a={qiunDataCharts:function(){return Promise.all([n.e("common/vendor"),n.e("uni_modules/qiun-data-charts/components/qiun-data-charts/qiun-data-charts")]).then(n.bind(null,"3f77"))}},r=function(){var t=this.$createElement;this._self._c},i=[]},"7a9d":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var a=n("2953"),r={data:function(){return{chartData:{},opts:{color:["#91CB74","#FAC858"],padding:[15,15,0,5],enableScroll:!1,legend:{},xAxis:{disableGrid:!0},yAxis:{data:[{min:0}]},extra:{column:{type:"group",width:30,activeBgColor:"#000000",activeBgOpacity:.08,linearType:"custom",seriesGap:5,linearOpacity:.5,barBorderCircle:!0,customColor:["#91CB74","#FAC858"]}}}}},onReady:function(){this.getServerData()},methods:{getServerData:function(){var t=this;(0,a.taskColumn)().then((function(e){var n={categories:e.result.categories,series:e.result.series};t.chartData=JSON.parse(JSON.stringify(n))}))}}};e.default=r}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/statistics/components/taskColumn-create-component',
    {
        'pages/statistics/components/taskColumn-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('df3c')['createComponent'](__webpack_require__("22f0"))
        })
    },
    [['pages/statistics/components/taskColumn-create-component']]
]);
