(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/thorui/tui-icon/tui-icon"],{1556:function(t,n,i){"use strict";i.r(n);var e=i("cf7d"),u=i("fda1");for(var c in u)["default"].indexOf(c)<0&&function(t){i.d(n,t,(function(){return u[t]}))}(c);i("6f22");var o=i("828b"),r=Object(o["a"])(u["default"],e["b"],e["c"],!1,null,"b950cf4c",null,!1,e["a"],void 0);n["default"]=r.exports},"5c03":function(t,n,i){},"6f22":function(t,n,i){"use strict";var e=i("5c03"),u=i.n(e);u.a},ba1f:function(t,n,i){"use strict";(function(t){var e=i("47a9");Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var u=e(i("b8937")),c={name:"tuiIcon",emits:["click"],props:{name:{type:String,default:""},customPrefix:{type:String,default:""},size:{type:[Number,String],default:0},unit:{type:String,default:""},color:{type:String,default:""},bold:{type:Boolean,default:!1},margin:{type:String,default:"0"},index:{type:Number,default:0}},computed:{getColor:function(){return this.color||t&&t.$tui&&t.$tui.tuiIcon.color||"#999"},getSize:function(){var n=this.size||t&&t.$tui&&t.$tui.tuiIcon.size||32,i=this.unit||t&&t.$tui&&t.$tui.tuiIcon.unit||"px";return n+i}},data:function(){return{icons:u.default}},methods:{handleClick:function(){this.$emit("click",{index:this.index})}}};n.default=c}).call(this,i("df3c")["default"])},cf7d:function(t,n,i){"use strict";i.d(n,"b",(function(){return e})),i.d(n,"c",(function(){return u})),i.d(n,"a",(function(){}));var e=function(){var t=this.$createElement;this._self._c},u=[]},fda1:function(t,n,i){"use strict";i.r(n);var e=i("ba1f"),u=i.n(e);for(var c in e)["default"].indexOf(c)<0&&function(t){i.d(n,t,(function(){return e[t]}))}(c);n["default"]=u.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/thorui/tui-icon/tui-icon-create-component',
    {
        'components/thorui/tui-icon/tui-icon-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('df3c')['createComponent'](__webpack_require__("1556"))
        })
    },
    [['components/thorui/tui-icon/tui-icon-create-component']]
]);
